In [12]:
import os
import tensorflow as tf
from tensorflow.keras.utils import load_img, img_to_array
from PIL import Image
import numpy as np

os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"

In [13]:
#load model
model = tf.keras.models.load_model('./saved_model/93% accuracy (Kaleng, Kertas, Minyak dan Organik)')

In [17]:
test_img = "./test"

class_names = ["kaleng","kertas","minyak","organik"]

test=[]

for fn in os.listdir(test_img):
 
  # predicting images
  path = os.path.join(test_img,fn)
  img = load_img(path, target_size=(225, 225))
  x = img_to_array(img)
  x = np.expand_dims(x, axis=0)

  images = np.vstack([x])
  classes = model.predict(images)
  print(fn)
  print( classes)
  print("Prediction : " + class_names[np.argmax(classes)] + "\n")

1/1 [==============================] - 0s 36ms/step
gunting.jpg
[[9.9994421e-01 5.7874170e-36 5.5842203e-05 0.0000000e+00]]
Prediction : kaleng

1/1 [==============================] - 0s 29ms/step
Image_1.jpg
[[9.9999928e-01 7.2005531e-07 4.4701992e-13 6.6910765e-31]]
Prediction : kaleng

1/1 [==============================] - 0s 26ms/step
kaleng01.jpg
[[1.0000000e+00 0.0000000e+00 4.2932946e-22 0.0000000e+00]]
Prediction : kaleng

1/1 [==============================] - 0s 35ms/step
kaleng02.jpg
[[1.0000000e+00 0.0000000e+00 0.0000000e+00 3.6555735e-38]]
Prediction : kaleng

1/1 [==============================] - 0s 31ms/step
kaleng03.jpg
[[1.0000000e+00 0.0000000e+00 2.0808604e-28 0.0000000e+00]]
Prediction : kaleng

1/1 [==============================] - 0s 27ms/step
kaleng04.jpg
[[1.000000e+00 0.000000e+00 7.637883e-35 0.000000e+00]]
Prediction : kaleng

1/1 [==============================] - 0s 31ms/step
kaleng05.jpg
[[1.0000000e+00 0.0000000e+00 3.5333257e-11 0.0000000e+00]]
Predi